imagine.lua
cubzh/worlds pull request #6
Opened 2023-07-06 15:04 UTC by vitawrap

2023-07-17 17:10 UTC, aduermael commented on caillef/imagine.lua
> +Pointer.Drag2Begin = function(pe)
Please remove empty functions! 🙂

2023-07-17 17:10 UTC, aduermael commented on caillef/imagine.lua
>  Pointer.Down = function(pe)
Please remove empty functions! 🙂

2023-07-17 17:10 UTC, aduermael commented on caillef/imagine.lua
>  Pointer.Up = function(pe)
Please remove empty functions! 🙂

2023-07-18 20:39 UTC, vitawrap commented
Adressed the review and hopefully removed all of the dangling deprecated stuff!

2023-07-21 06:03 UTC, aduermael requested changes
The quality of the game has clearly improved! Well done @vitawrap! 
Still a few issues, and not all of them really due to that PR: 

**Clicking on a generated image doesn't show info:**

<img width="1190" alt="Screenshot 2023-07-21 at 07 42 30" src="https://github.com/cubzh/worlds/assets/6775074/1c34366d-8948-4152-8d87-cf87b26940be">

**Create Image buttons are not positioned like text inputs (they should be):**

<img width="1190" alt="Screenshot 2023-07-21 at 07 40 19" src="https://github.com/cubzh/worlds/assets/6775074/bb8f419a-6937-4959-a4b7-d8a23cdcb961">


This is for @ArthurVoxowl (and I), `TextBubble` may need to be fixed following the PR about texts.

<img width="1190" alt="Screenshot 2023-07-21 at 07 39 03" src="https://github.com/cubzh/worlds/assets/6775074/7db25078-1550-4699-b4c3-7813ef572b6d">

Also, using semi transparent color for texts created depth / blending issues in the UI:

<img width="1190" alt="Screenshot 2023-07-21 at 07 40 31" src="https://github.com/cubzh/worlds/assets/6775074/5e394d58-9d11-42a7-9831-85531a2d835e">

2023-07-27 15:53 UTC, aduermael approved these changes
LGTM! 
Merging now, addressing my comments in following PR. 🙂

2023-07-27 15:53 UTC, merged